import {request as rawRequest,scene,refresh} from './game.js';
import * as THREE from 'three';
const result={checks:[],errors:[]};window.addEventListener('error',e=>result.errors.push(e.message));window.addEventListener('unhandledrejection',e=>result.errors.push(String(e.reason)));
const wait=async condition=>{for(let n=0;n<150;n++){if(await condition())return;await new Promise(r=>setTimeout(r,40));}throw new Error('Timed out waiting for browser state.');};
const request=rawRequest;
const state=async()=>JSON.parse(await request('save',null));
const check=async(name,run)=>{result.currentCheck=name;await run();result.checks.push(name);};
const assert=(value,message)=>{if(!value)throw new Error(message);};
const tool=name=>document.querySelector(`[data-tool="${name}"]`).click();
function clickWorld(x,y,z=4){scene.renderer.render(scene.scene,scene.camera);scene.controls.update();scene.camera.updateMatrixWorld();const p=new THREE.Vector3(x*4+2,z,y*4+2).project(scene.camera),rect=scene.renderer.domElement.getBoundingClientRect(),event={clientX:rect.left+(p.x+1)*rect.width/2,clientY:rect.top+(1-p.y)*rect.height/2,button:0,pointerId:1,bubbles:true};scene.controls.enabled=false;const viewport=document.getElementById('viewport');viewport.dispatchEvent(new PointerEvent('pointerdown',event));viewport.dispatchEvent(new PointerEvent('pointerup',event));scene.controls.enabled=true;}
try{
 await wait(()=>document.getElementById('cash').textContent!=='—');window.confirm=()=>true;document.getElementById('new').click();await wait(async()=>{const s=await state();return s.rides.length===1&&s.facilities.length===3;});await refresh(true);
 await check('WebGL scene and Classic controls render',async()=>{scene.renderer.render(scene.scene,scene.camera);assert(scene.renderer.info.render.triangles>0,'No scene geometry rendered');assert(document.querySelectorAll('[data-tool]').length===7,'Classic tools missing');assert(document.querySelector('canvas').width===1920,'Unexpected render width');});
 await check('Pause suppresses actual worker updates',async()=>{document.getElementById('pause').click();await wait(async()=>(await state()).paused);const before=await state();assert(await request('advance',40)===0,'Paused engine advanced');assert((await state()).tick===before.tick,'Paused clock changed');});
 await check('Speed controls update through worker replies',async()=>{document.querySelector('[data-speed="4"]').click();await wait(()=>document.querySelector('[data-speed="4"]').classList.contains('active'));document.querySelector('[data-speed="1"]').click();await wait(()=>document.querySelector('[data-speed="1"]').classList.contains('active'));});
 await check('Pointer path placement charges the authoritative price',async()=>{tool('path');const before=await state();clickWorld(23,12);await wait(async()=>(await state()).elements.some(e=>e.kind==='path'&&e.tile.x===23&&e.tile.y===12));const after=await state();assert(before.cash-after.cash===12,'Wrong placement payment');});
 await check('Rejected duplicate placement preserves money and state',async()=>{const before=await state();clickWorld(23,12);await wait(()=>document.getElementById('feedback').classList.contains('error'));const after=await state();assert(JSON.stringify(before)===JSON.stringify(after),'Rejected placement mutated state');});
 await check('New coaster, station, append and partial refund use real commands',async()=>{tool('track');document.getElementById('new-coaster').click();document.getElementById('new-ride-name').value='Browser Probe';clickWorld(30,12);await wait(async()=>(await state()).rides.some(r=>r.name==='Browser Probe'));await refresh(true);document.getElementById('build-track').click();await wait(async()=>(await state()).rides.find(r=>r.name==='Browser Probe').track.length===1);document.querySelector('[data-sub="flat"]').click();await new Promise(r=>setTimeout(r,120));const before=await state();document.getElementById('build-track').click();await wait(async()=>(await state()).rides.find(r=>r.name==='Browser Probe').track.length===2);document.getElementById('remove-track').click();await wait(async()=>(await state()).rides.find(r=>r.name==='Browser Probe').track.length===1);const after=await state();assert(before.cash-after.cash===31,'Demolition substituted full refund');});
 await check('Loan control moves cash and principal without income',async()=>{document.getElementById('finance').click();const before=await state();document.getElementById('loan').value='1000';document.getElementById('set-loan').click();await wait(async()=>(await state()).loan===10000);const after=await state();assert(after.cash-before.cash===10000,'Loan cash mismatch');assert(JSON.stringify(after.ledger)===JSON.stringify(before.ledger),'Borrowing changed income');document.getElementById('finance-dialog').close();});
 await check('Facility inspection edits current price and opening state',async()=>{document.getElementById('clear-selection').click();await wait(()=>document.querySelector('[data-select-facility]'));document.querySelector('[data-select-facility]').click();await wait(()=>document.getElementById('facility-price'));const s=await state(),f=s.facilities[0];document.getElementById('facility-price').value='2.5';document.getElementById('facility-price-apply').click();await wait(async()=>(await state()).facilities.find(x=>x.id===f.id).price===25);await refresh(true);document.getElementById('facility-toggle').click();await wait(async()=>!(await state()).facilities.find(x=>x.id===f.id).open);});
 let hired;
 await check('Staff placement and instanced picking select a real employee',async()=>{tool('staff');const before=await state();clickWorld(23,12);await wait(async()=>(await state()).staff.length===before.staff.length+1);hired=(await state()).staff.find(t=>t.point.x===23&&t.point.y===12);assert(hired,'Employee absent');await refresh(true);tool('inspect');clickWorld(23,12,4.63);await wait(()=>document.getElementById('staff-patrol'));assert(document.getElementById('inspection').textContent.includes(String(hired.id)),'Wrong instanced selection');});
 await check('Patrol painting reaches authoritative staff state',async()=>{document.getElementById('staff-patrol').click();clickWorld(23,12);await wait(async()=>(await state()).staff.find(t=>t.id===hired.id).patrol.length===2048);});
 await check('Browser save reaches IndexedDB and import preserves state',async()=>{document.getElementById('save').click();await wait(()=>document.getElementById('save-status').textContent.startsWith('Saved '));const before=await request('save',null);const transfer=new DataTransfer();transfer.items.add(new File([before],'park.json',{type:'application/json'}));const input=document.getElementById('import-file');input.files=transfer.files;input.dispatchEvent(new Event('change'));await wait(()=>document.getElementById('feedback').textContent==='Park imported successfully.');assert(await request('save',null)===before,'Round-trip changed state');});
 await check('Invalid imports report structured failure and keep the park',async()=>{const before=await request('save',null);const transfer=new DataTransfer();transfer.items.add(new File(['{"version":999}'],'broken.json',{type:'application/json'}));const input=document.getElementById('import-file');input.files=transfer.files;input.dispatchEvent(new Event('change'));await wait(()=>document.getElementById('feedback').textContent.startsWith('Import failed:'));assert(document.getElementById('feedback').classList.contains('error'),'Import error is not visible');assert(await request('save',null)===before,'Failed import replaced park');});
 await check('Static scene replacement disposes obsolete instanced ground buffers',async()=>{const ground=scene.staticGroup.children.find(o=>o.isInstancedMesh&&o.userData.ground);assert(ground,'Ground instance absent');let disposed=0;ground.addEventListener('dispose',()=>disposed++);await refresh(true);await wait(()=>disposed===1);});
 await check('Forced static refresh survives an already pending view',async()=>{const s=await state();s.terrain[25*256+25]=48;await request('load',JSON.stringify(s));const pendingView=refresh();await refresh(true);await pendingView;const height=()=>{const ground=scene.staticGroup.children.find(o=>o.isInstancedMesh&&o.userData.ground),m=new THREE.Matrix4();ground.getMatrixAt(25*48+25,m);return m.elements[13];};await wait(()=>height()===3);});
 await check('Staff list makes overlapping initial employees individually selectable',async()=>{document.getElementById('clear-selection').click();await wait(()=>document.querySelectorAll('[data-select-staff]').length>=2);const handyman=(await state()).staff.find(t=>t.role==='handyman');document.querySelector(`[data-select-staff="${handyman.id}"]`).click();await wait(()=>document.getElementById('staff-fire'));assert(document.getElementById('inspection').textContent.includes(`Handyman ${handyman.id}`),'Overlapped handyman has no inspector access');});
 await check('Unpause permits real worker guest arrivals',async()=>{tool('inspect');document.getElementById('pause').click();await wait(async()=>!(await state()).paused);await request('advance',160);await refresh(true);assert((await state()).people.guests.length>0,'No authoritative guests arrived');});
 assert(result.errors.length===0,'Browser exceptions: '+result.errors.join('; '));result.ok=true;result.state={tick:(await state()).tick,guests:(await state()).people.guests.length};
}catch(e){result.ok=false;result.failure=e.stack??String(e);}
scene.overview();scene.controls.update();scene.renderer.render(scene.scene,scene.camera);
const evidence=document.createElement('pre');evidence.id='browser-check-result';evidence.hidden=true;evidence.textContent=JSON.stringify(result);document.body.append(evidence);document.documentElement.dataset.browserChecks=result.ok?'passed':'failed';
