import {request as rawRequest,execute,scene,refresh} from './game.js';
import * as THREE from 'three';
import {newPark} from './content/steel-coaster.js';
import {WORKER_PROTOCOL_VERSION} from './simulation/protocol.js';
const result={checks:[],errors:[]};window.addEventListener('error',e=>result.errors.push(e.message));window.addEventListener('unhandledrejection',e=>result.errors.push(String(e.reason)));
window.browserCheckEvidence=result;
const wait=async condition=>{for(let n=0;n<150;n++){if(await condition())return;await new Promise(r=>setTimeout(r,40));}throw new Error('Timed out waiting for browser state.');};
const request=rawRequest;
const state=async()=>JSON.parse(await request('save',null));
const check=async(name,run)=>{result.currentCheck=name;await run();result.checks.push(name);};
const assert=(value,message)=>{if(!value)throw new Error(message);};
const tool=name=>document.querySelector(`[data-tool="${name}"]`).click();
function clickWorld(x,y,z=4){scene.renderer.render(scene.scene,scene.camera);scene.controls.update();scene.camera.updateMatrixWorld();const p=new THREE.Vector3(x*4+2,z,y*4+2).project(scene.camera),rect=scene.renderer.domElement.getBoundingClientRect(),event={clientX:rect.left+(p.x+1)*rect.width/2,clientY:rect.top+(1-p.y)*rect.height/2,button:0,pointerId:1,bubbles:true};scene.controls.enabled=false;const viewport=document.getElementById('viewport');viewport.dispatchEvent(new PointerEvent('pointerdown',event));viewport.dispatchEvent(new PointerEvent('pointerup',event));scene.controls.enabled=true;}
function elementBounds(id){const bounds=new THREE.Box3(),matrix=new THREE.Matrix4();scene.staticGroup.updateMatrixWorld(true);scene.staticGroup.traverse(mesh=>{if(!mesh.isMesh)return;mesh.geometry.computeBoundingBox();if(mesh.userData.selections){mesh.userData.selections.forEach((selected,i)=>{if(selected?.kind==='element'&&selected.id===id){mesh.getMatrixAt(i,matrix);matrix.premultiply(mesh.matrixWorld);bounds.union(mesh.geometry.boundingBox.clone().applyMatrix4(matrix));}});}else{let parent=mesh;while(parent&&!parent.userData.selection)parent=parent.parent;if(parent?.userData.selection.id===id)bounds.union(mesh.geometry.boundingBox.clone().applyMatrix4(mesh.matrixWorld));}});return bounds;}
try{
 await wait(()=>!document.body.inert);window.confirm=()=>true;document.getElementById('new').click();await wait(()=>document.getElementById('feedback').textContent==='A new park is ready.');await wait(()=>document.getElementById('pause').textContent==='Ⅱ');await refresh(true);const preparation=await state();for(const e of preparation.elements)if(e.kind==='scenery'&&(e.tile.x>=21&&e.tile.x<=26&&e.tile.y>=10&&e.tile.y<=14||[[30,12],[25,25]].some(([x,y])=>e.tile.x===x&&e.tile.y===y)))await execute({type:'remove-scenery',id:e.id});await refresh(true);
 await check('WebGL scene and Classic controls render',async()=>{scene.renderer.render(scene.scene,scene.camera);assert(scene.renderer.getContext().getError()===0,'WebGL rendering error');assert(scene.renderer.info.render.triangles>0,'No scene geometry rendered');assert(document.querySelectorAll('[data-tool]').length===8,'Classic tools missing');assert(document.querySelector('canvas').width===1920,'Unexpected render width');});
 await check('Legal elevated paths clear detailed station, portal and shop roofs',async()=>{const s=await state(),targets=[s.elements.find(e=>e.kind==='track'&&e.piece==='station'),s.elements.find(e=>e.kind==='portal'),s.elements.find(e=>e.kind==='facility')];for(const e of targets){const bounds=elementBounds(e.id),height=e.kind==='track'?e.origin.z:e.height,tile=e.kind==='track'?{x:e.origin.x/32,y:e.origin.y/32}:e.tile;assert(!bounds.isEmpty()&&bounds.max.y<=height/8+2.001,'Detailed model exceeds legal overhead clearance');if(e.kind!=='track')assert(bounds.min.x>=tile.x*4-.001&&bounds.max.x<=(tile.x+1)*4+.001&&bounds.min.z>=tile.y*4-.001&&bounds.max.z<=(tile.y+1)*4+.001,'Building extends into a neighboring tile');assert(await execute({type:'place-path',tile,height:height+16,queueFor:null}),'Legal overhead path rejected');}await refresh(true);});
 await check('Pause suppresses actual worker updates',async()=>{document.getElementById('pause').click();await wait(async()=>(await state()).paused);const before=await state();assert(await request('advance',40)===0,'Paused engine advanced');assert((await state()).tick===before.tick,'Paused clock changed');});
 await check('A valid steel-only v7 file import adds current identities and profiles without changing legacy park values',async()=>{const before=await state(),source=newPark(JSON.parse(before.rules));for(const e of source.snapshot().elements)if(e.kind==='scenery'&&(e.tile.x>=21&&e.tile.x<=26&&e.tile.y>=10&&e.tile.y<=14||[[30,12],[25,25]].some(([x,y])=>e.tile.x===x&&e.tile.y===y)))assert(source.execute({type:'remove-scenery',id:e.id},source.revision).ok,'Legacy preparation failed');const legacy=source.snapshot();legacy.paused=true;delete legacy.contentVersion;delete legacy.nextInstance;delete legacy.carouselSessions;delete legacy.boats;delete legacy.retiredRideIncome;legacy.version=7;for(const g of legacy.people.guests){assert(g.held===null,'Legacy fixture contains a later product');delete g.held;}for(const r of [...legacy.rides,...legacy.facilities]){delete r.content;delete r.instanceId;}const rules=JSON.parse(legacy.rules);delete rules.rideProfiles;delete rules.fixedProfiles;delete rules.channelProfiles;delete rules.commerceProfiles;legacy.rules=JSON.stringify(rules);const transfer=new DataTransfer();transfer.items.add(new File([JSON.stringify(legacy)],'v7-park.json',{type:'application/json'}));const input=document.getElementById('import-file');input.files=transfer.files;input.dispatchEvent(new Event('change'));await wait(()=>document.getElementById('feedback').textContent==='Park imported successfully.');const migrated=await state();assert(migrated.version===12&&migrated.contentVersion===5,'Current format did not migrate');assert(migrated.rides.every(r=>r.content.familyId==='independent.circuit-coaster'),'Legacy rides were relabelled as original');const stripped=structuredClone(migrated);delete stripped.contentVersion;delete stripped.nextInstance;delete stripped.carouselSessions;delete stripped.boats;delete stripped.retiredRideIncome;stripped.version=7;for(const g of stripped.people.guests){assert(g.held===null,'Legacy migration created a product');delete g.held;}for(const r of [...stripped.rides,...stripped.facilities]){delete r.content;delete r.instanceId;}const migratedRules=JSON.parse(stripped.rules);delete migratedRules.rideProfiles;delete migratedRules.fixedProfiles;delete migratedRules.channelProfiles;delete migratedRules.commerceProfiles;stripped.rules=JSON.stringify(migratedRules);assert(JSON.stringify(stripped)===JSON.stringify(legacy),'Migration changed legacy rules or park state');await refresh(true);assert(scene.packet.protocolVersion===WORKER_PROTOCOL_VERSION&&scene.packet.rides[0].presentation.kind==='procedural-coaster','Migrated presentation did not render');document.getElementById('export').click();await wait(()=>document.getElementById('feedback').textContent.startsWith('Park exported.'));});
 await check('Unsupported original content cannot allocate a ride through the actual worker',async()=>{const before=await request('save',null);let rejected=false;try{await request('quote',{type:'create-ride',name:'Wooden reference',tile:{x:30,y:30},height:32,direction:0,content:{familyId:'reference.rct2.family.wooden-rc',variantId:'reference.rct2.variant.ptct1',modeId:'reference.rct2.mode.continuousCircuit'}});}catch(e){rejected=e.message.includes('no executable');}assert(rejected,'Unimplemented wooden reference borrowed the steel adapter');assert(await request('save',null)===before,'Rejected content changed resources');const directory=await request('catalogue',null);assert(directory.contentVersion===5&&directory.variants.filter(v=>v.reference).length===155,'Worker lost base content variants');});
 await check('Speed controls update through worker replies',async()=>{document.querySelector('[data-speed="4"]').click();await wait(()=>document.querySelector('[data-speed="4"]').classList.contains('active'));document.querySelector('[data-speed="1"]').click();await wait(()=>document.querySelector('[data-speed="1"]').classList.contains('active'));});
 await check('Pointer path placement charges the authoritative price',async()=>{tool('path');const before=await state();clickWorld(23,12);await wait(async()=>(await state()).elements.some(e=>e.kind==='path'&&e.tile.x===23&&e.tile.y===12));const after=await state();assert(before.cash-after.cash===12,'Wrong placement payment');});
 await check('A shop side wall retains its path border while its real frontage stays open',async()=>{const s=await state(),shop=s.elements.find(e=>e.kind==='facility'&&e.direction===2),tile={x:shop.tile.x+1,y:shop.tile.y};assert(await execute({type:'place-path',tile,height:shop.height,queueFor:null}),'Side path placement failed');const path=(await state()).elements.find(e=>e.kind==='path'&&e.tile.x===tile.x&&e.tile.y===tile.y);await refresh(true);await wait(()=>scene.elements.some(e=>e.id===path.id));assert(elementBounds(path.id).min.x<=tile.x*4+.005,'The shop side wall is falsely shown as an entrance');const front=s.elements.find(e=>e.kind==='path'&&e.tile.x===shop.tile.x-1&&e.tile.y===shop.tile.y);assert(elementBounds(front.id).max.x<(front.tile.x+1)*4-.03,'The actual shop frontage is fenced off');});
 await check('Rejected duplicate placement preserves money and state',async()=>{const before=await state();clickWorld(23,12);await wait(()=>document.getElementById('feedback').classList.contains('error'));const after=await state();assert(JSON.stringify(before)===JSON.stringify(after),'Rejected placement mutated state');});
 await check('New coaster, station, append and partial refund use real commands',async()=>{tool('track');document.getElementById('new-coaster').click();document.getElementById('new-ride-name').value='Browser Probe';clickWorld(30,12);await wait(async()=>(await state()).rides.some(r=>r.name==='Browser Probe'));await refresh(true);document.getElementById('build-track').click();await wait(async()=>(await state()).rides.find(r=>r.name==='Browser Probe').track.length===1);document.querySelector('[data-sub="flat"]').click();await new Promise(r=>setTimeout(r,120));const before=await state();document.getElementById('build-track').click();await wait(async()=>(await state()).rides.find(r=>r.name==='Browser Probe').track.length===2);document.getElementById('remove-track').click();await wait(async()=>(await state()).rides.find(r=>r.name==='Browser Probe').track.length===1);const after=await state();assert(before.cash-after.cash===31,'Demolition substituted full refund');});
 await check('Loan control moves cash and principal without income',async()=>{document.getElementById('finance').click();const before=await state();document.getElementById('loan').value='1000';document.getElementById('set-loan').click();await wait(async()=>(await state()).loan===10000);const after=await state();assert(after.cash-before.cash===10000,'Loan cash mismatch');assert(JSON.stringify(after.ledger)===JSON.stringify(before.ledger),'Borrowing changed income');document.getElementById('finance-dialog').close();});
 await check('Facility inspection edits current price and opening state',async()=>{document.getElementById('clear-selection').click();await wait(()=>document.querySelector('[data-select-facility]'));document.querySelector('[data-select-facility]').click();await wait(()=>document.getElementById('facility-price'));const s=await state(),f=s.facilities[0];document.getElementById('facility-price').value='2.5';document.getElementById('facility-price-apply').click();await wait(async()=>(await state()).facilities.find(x=>x.id===f.id).price===25);await refresh(true);document.getElementById('facility-toggle').click();await wait(async()=>!(await state()).facilities.find(x=>x.id===f.id).open);});
 let hired;
 await check('Staff placement and instanced picking select a real employee',async()=>{tool('staff');const before=await state();clickWorld(23,12);await wait(async()=>(await state()).staff.length===before.staff.length+1);hired=(await state()).staff.find(t=>t.point.x===23&&t.point.y===12);assert(hired,'Employee absent');await refresh(true);tool('inspect');clickWorld(23,12,4.63);await wait(()=>document.getElementById('staff-patrol'));assert(document.getElementById('inspection').textContent.includes(String(hired.id)),'Wrong instanced selection');});
 await check('Patrol painting reaches authoritative staff state',async()=>{document.getElementById('staff-patrol').click();clickWorld(23,12);await wait(async()=>(await state()).staff.find(t=>t.id===hired.id).patrol.length===2048);});
 await check('A rejected patrol tile leaves later valid painting usable',async()=>{const before=(await state()).staff.find(t=>t.id===hired.id).patrol;clickWorld(0,10);await wait(()=>document.getElementById('feedback').classList.contains('error'));assert(JSON.stringify((await state()).staff.find(t=>t.id===hired.id).patrol)===JSON.stringify(before),'Rejected patrol changed the authoritative area');clickWorld(24,12);const bit=12*256+24;await wait(async()=>((await state()).staff.find(t=>t.id===hired.id).patrol[bit>>>5]&(1<<(bit&31)))!==0);});
 await check('Rapid valid patrol clicks commit in order without a false stale error',async()=>{clickWorld(25,12);clickWorld(26,12);await wait(async()=>{const p=(await state()).staff.find(t=>t.id===hired.id).patrol;return[25,26].every(x=>{const bit=12*256+x;return(p[bit>>>5]&(1<<(bit&31)))!==0;});});assert(!document.getElementById('feedback').classList.contains('error'),'Valid patrol painting reported a rejected revision');});
 await check('Scenery clicks pay the quote and batched picking removes the selected lantern',async()=>{tool('scenery');document.querySelector('[data-sub="lamp"]').click();const before=await state();clickWorld(24,12);await wait(async()=>(await state()).elements.some(e=>e.kind==='scenery'&&e.tile.x===24&&e.tile.y===12));const lamp=(await state()).elements.find(e=>e.kind==='scenery'&&e.tile.x===24&&e.tile.y===12);assert(before.cash-(await state()).cash===70,'Wrong scenery cost');await refresh(true);await wait(()=>scene.elements.some(e=>e.id===lamp.id));tool('inspect');clickWorld(24,12,6.7);await wait(()=>document.getElementById('inspector-title').textContent==='Park lantern');document.getElementById('element-remove').click();await wait(async()=>!(await state()).elements.some(e=>e.kind==='scenery'&&e.tile.x===24&&e.tile.y===12));assert((await state()).cash===before.cash-35,'Wrong scenery removal refund');});
 await check('Focused dialog buttons retain native Space and do not toggle park pause',async()=>{document.getElementById('finance').click();const button=document.querySelector('#finance-dialog button');button.focus();const before=(await state()).paused,event=new KeyboardEvent('keydown',{code:'Space',key:' ',bubbles:true,cancelable:true});button.dispatchEvent(event);assert(!event.defaultPrevented,'Space was hijacked from a focused button');assert((await state()).paused===before,'Dialog keyboard changed pause');document.getElementById('finance-dialog').close();});
 await check('Browser save reaches IndexedDB and import preserves state',async()=>{document.getElementById('save').click();await wait(()=>document.getElementById('save-status').textContent.startsWith('Saved '));const before=await request('save',null);const transfer=new DataTransfer();transfer.items.add(new File([before],'park.json',{type:'application/json'}));const input=document.getElementById('import-file');input.files=transfer.files;input.dispatchEvent(new Event('change'));await wait(()=>document.getElementById('feedback').textContent==='Park imported successfully.');assert(await request('save',null)===before,'Round-trip changed state');});
 await check('Invalid imports report structured failure and keep the park',async()=>{const before=await request('save',null);const transfer=new DataTransfer();transfer.items.add(new File(['{"version":999}'],'broken.json',{type:'application/json'}));const input=document.getElementById('import-file');input.files=transfer.files;input.dispatchEvent(new Event('change'));await wait(()=>document.getElementById('feedback').textContent.startsWith('Import failed:'));assert(document.getElementById('feedback').classList.contains('error'),'Import error is not visible');assert(await request('save',null)===before,'Failed import replaced park');});
 await check('Static scene replacement disposes obsolete instanced ground buffers',async()=>{const ground=scene.staticGroup.children.find(o=>o.isInstancedMesh&&o.userData.ground);assert(ground,'Ground instance absent');let disposed=0;ground.addEventListener('dispose',()=>disposed++);await refresh(true);await wait(()=>disposed===1);});
 await check('Forced static refresh survives an already pending view',async()=>{const s=await state();s.terrain[25*256+25]=48;await request('load',JSON.stringify(s));const pendingView=refresh();await refresh(true);await pendingView;const height=()=>{const ground=scene.staticGroup.children.find(o=>o.isInstancedMesh&&o.userData.ground),m=new THREE.Matrix4();ground.getMatrixAt(25*48+25,m);return m.elements[13];};await wait(()=>height()===3);});
 await check('Staff list makes overlapping initial employees individually selectable',async()=>{document.getElementById('clear-selection').click();await wait(()=>document.querySelectorAll('[data-select-staff]').length>=2);const handyman=(await state()).staff.find(t=>t.role==='handyman');document.querySelector(`[data-select-staff="${handyman.id}"]`).click();await wait(()=>document.getElementById('staff-fire'));assert(document.getElementById('inspection').textContent.includes(`Handyman ${handyman.id}`),'Overlapped handyman has no inspector access');});
 await check('Malformed Worker envelopes return correlated errors and preserve a subsequent save',async()=>{await new Promise((resolve,reject)=>{const probe=new Worker('./simulation/browser-worker.js',{type:'module'}),replies=new Map(),timer=setTimeout(()=>finish(new Error('Worker boundary did not reply')),10000);function finish(error){clearTimeout(timer);probe.terminate();error?reject(error):resolve();}probe.onerror=e=>{e.preventDefault();finish(new Error('Worker envelope threw: '+e.message));};probe.onmessage=e=>{const m=e.data;if(m.event==='ready'){probe.postMessage({protocolVersion:WORKER_PROTOCOL_VERSION,id:901});probe.postMessage({protocolVersion:WORKER_PROTOCOL_VERSION,id:902,request:null});probe.postMessage({protocolVersion:WORKER_PROTOCOL_VERSION,id:903,request:{type:'save',payload:null}});return;}if(![901,902,903].includes(m.id))return;replies.set(m.id,m.result);if(replies.size===3){try{for(const id of[901,902])assert(replies.get(id).ok===false&&replies.get(id).error.code==='INVALID_COMMAND','Missing correlated envelope error');assert(replies.get(903).ok&&JSON.parse(replies.get(903).value).version===12,'Valid save was lost after envelope rejection');finish();}catch(error){finish(error);}}};});});
 await check('Unpause permits real worker guest arrivals',async()=>{tool('inspect');document.getElementById('pause').click();await wait(async()=>!(await state()).paused);await request('advance',160);await refresh(true);assert((await state()).people.guests.length>0,'No authoritative guests arrived');});
 await check('Only actual employees carry rendered work equipment',async()=>{await wait(()=>scene.packet.people.some((value,i)=>i%6===5&&value===0));const staff=scene.packet.people.filter((value,i)=>i%6===5&&value===1).length,tools=scene.people.group.children.find(mesh=>mesh.userData.staffTools);assert(tools?.count===staff,'Guest rows were assigned staff equipment');});
 await check('Final saved checkpoint preserves the validated park for page reload',async()=>{await execute({type:'set-paused',paused:true});await refresh(true);document.getElementById('save').click();await wait(()=>document.getElementById('feedback').textContent==='Your park has been saved in this browser.');});
 assert(result.errors.length===0,'Browser exceptions: '+result.errors.join('; '));result.ok=true;result.state={tick:(await state()).tick,guests:(await state()).people.guests.length};
}catch(e){result.ok=false;result.failure=e.stack??String(e);}
scene.overview();scene.controls.update();scene.renderer.render(scene.scene,scene.camera);
const evidence=document.createElement('pre');evidence.id='browser-check-result';evidence.hidden=true;evidence.textContent=JSON.stringify(result);document.body.append(evidence);document.documentElement.dataset.browserChecks=result.ok?'passed':'failed';
