import test from 'node:test';
import assert from 'node:assert/strict';
import {Engine} from '../dist/simulation/index.js';
import {apply,rules,options} from './fixtures.mjs';
function people(){const p=structuredClone(rules);p.guests.spawnTicks=200;p.guests.decisionTicks=1;p.guests.initialEnergy=100;p.guests.needGrowth=0;const e=new Engine(options,p);const paths=[10,11,12].map(x=>apply(e,{type:'place-path',tile:{x,y:10},height:32,queueFor:null}).id),bench=apply(e,{type:'place-amenity',kind:'bench',path:paths[0]}).id;apply(e,{type:'set-park-entrance',point:{x:10,y:10,z:32}});apply(e,{type:'set-park-open',open:true});assert(e.advance(200).ok);apply(e,{type:'set-park-open',open:false});return{e,p,paths,bench};}
test('another guest occupying a target bench does not make an earlier walking intention unloadable',()=>{
 const {e}=people(),s=e.snapshot(),g=s.people.guests[0];Object.assign(g,{phase:'walking',point:{x:12,y:10,z:32},goal:{x:10,y:10,z:32},next:null,walkProgress:0,restProgress:0});s.people.guests.push({...structuredClone(g),id:2,point:{x:10,y:10,z:32}});s.nextEntity=3;s.amenities[0].occupant=null;assert(e.restoreSave(JSON.stringify(s)).ok);assert(e.advance(1).ok);const after=e.snapshot();assert.equal(after.people.guests[1].phase,'resting');assert.equal(after.people.guests[0].phase,'walking');assert(e.restoreSave(e.exportSave()).ok);assert(e.advance(1).ok);assert.equal(e.snapshot().people.guests[0].amenity,null);
});
test('malformed guest positions return INVALID_SAVE instead of escaping the host as TypeError',()=>{
 const {e}=people();assert(e.advance(1).ok);const original=e.exportSave();for(const point of [null,[],{x:10,y:10},'broken']){const s=JSON.parse(original);s.people.guests[0].point=point;const response=e.restoreSave(JSON.stringify(s));assert.equal(response.ok,false);assert.equal(response.error.code,'INVALID_SAVE');assert.equal(e.exportSave(),original);}
});
test('a removed cleaner next step cancels stale movement even when an alternate route remains',()=>{
 const {e,paths}=people(),s=e.snapshot();s.people.guests=[];s.litter=[{id:1,point:{x:10,y:10,z:32}}];s.nextEntity=2;s.amenities[0].occupant=null;assert(e.restoreSave(JSON.stringify(s)).ok);for(const [x,y] of [[12,11],[11,11],[10,11]])apply(e,{type:'place-path',tile:{x,y},height:32,queueFor:null});apply(e,{type:'hire-staff',role:'handyman',point:{x:12,y:10,z:32}});assert(e.advance(1).ok);assert.deepEqual(e.snapshot().staff[0].next,{x:11,y:10,z:32});apply(e,{type:'remove-path',id:paths[1]});assert.equal(e.snapshot().staff[0].cleanup,null);assert(e.restoreSave(e.exportSave()).ok);assert(e.advance(60).ok);assert.equal(e.snapshot().litter.length,0);assert(e.restoreSave(e.exportSave()).ok);
});
test('a last-slot bin deposit preserves another pending walking intention for next-tick recovery',()=>{
 const {e,paths,bench}=people();apply(e,{type:'remove-amenity',id:bench});const bin=apply(e,{type:'place-amenity',kind:'bin',path:paths[0]}).id,s=e.snapshot(),g=s.people.guests[0];s.amenities[0].fill=rules.housekeeping.binCapacity-1;Object.assign(g,{amenity:bin,phase:'walking',point:{x:12,y:10,z:32},goal:{x:10,y:10,z:32},next:null,walkProgress:0,restProgress:0,wrapper:true,wrapperTick:s.tick});s.people.guests.push({...structuredClone(g),id:2,point:{x:10,y:10,z:32}});s.nextEntity=3;assert(e.restoreSave(JSON.stringify(s)).ok);assert(e.advance(1).ok);assert.equal(e.snapshot().amenities[0].fill,rules.housekeeping.binCapacity);assert(e.restoreSave(e.exportSave()).ok);assert(e.advance(1).ok);assert.equal(e.snapshot().people.guests[0].amenity,null);assert(e.restoreSave(e.exportSave()).ok);
});
