import type { PieceRule, Rules, Vector } from '../simulation/types.js';
export declare const flumeProfileId = "independent.log-flume-v1";
export declare const flumePieceIds: readonly ['station', 'channel', 'splash', 'left', 'right', 'lift-start', 'lift', 'lift-end', 'drop-start', 'drop', 'drop-end'];
export type FlumePieceId = typeof flumePieceIds[number];
export declare const flumeCandidate: {
    tickHz: number;
    tileMetres: number;
    innerWidthMm: number;
    outerWidthMm: number;
    stationWidthMm: number;
    floorMm: number;
    waterMm: number;
    wallMm: number;
    platformMm: number;
    envelopeUnits: number;
    maxSupport: number;
    hullHalfLengthMm: number;
    channelSpeed: number;
    liftSpeed: number;
    acceleration: number;
    channelBrake: number;
    liftBrake: number;
    splashBrake: number;
    maxSpeed: number;
    gravity: number;
    boardTicks: number;
    minLoadTicks: number;
    maxLoadTicks: number;
    unloadTicks: number;
    defaultPrice: number;
    maxPrice: number;
    portalPrice: number;
    portalHeight: number;
    upkeep: number;
    inspectionInterval: number;
    inspectionTicks: number;
    repairTicks: number;
    happiness: number;
    nausea: number;
    seats: {
        x: number;
        y: number;
        z: number;
    }[];
};
export type FlumeProfile = typeof flumeCandidate;
export declare function withFlumeProfile(rules: Rules): Rules;
export declare function flumeLocalFrame(piece: FlumePieceId, t: number): {
    point: Vector;
    direction: Vector;
    up: Vector;
};
export declare const flumePieces: Record<FlumePieceId, PieceRule>;
