import {ParkScene} from './park-scene.js';
const legacySaveSlot=new URLSearchParams(location.search).get('showcase')==='classic'?'showcase-classic':'current',previousSaveSlot=legacySaveSlot+'-v9',saveSlot=legacySaveSlot+'-v10';
import {steelRules} from './content/steel-coaster.js';
import {WORKER_PROTOCOL_VERSION} from './simulation/protocol.js';
import {createContentBrowser} from './content-browser.js';
import {legacyRideContent,legacyFacilityContent} from './content/registry.js';
const $=id=>document.getElementById(id),escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>'$'+(n/10).toLocaleString('en',{minimumFractionDigits:2,maximumFractionDigits:2});
const scene=new ParkScene($('viewport')),worker=new Worker('./simulation/browser-worker.js',{type:'module'}),pending=new Map();
let localSaveAllowed=true;
let serial=0,ready=false,packet=null,staticRevision=null,staticRequested=true,staticEpoch=0,requesting=false,tool='inspect',subtool='flat',selectedRide=0,selection=null,hover=null,quoted=null,quoteSequence=0,previewTimer=null,inspectSignature='',lastInspect=0,patrolTiles=[];
let patrolUpdate=Promise.resolve();
let libraryCatalogue=null,selectedRideContent=legacyRideContent();
const selectedFacilityContent={food:legacyFacilityContent('food'),drink:legacyFacilityContent('drink'),restroom:legacyFacilityContent('restroom')};
const contentLibrary=createContentBrowser({loadCatalogue:async()=>{libraryCatalogue=await request('catalogue',null);return libraryCatalogue;},onChoose:content=>{
 const variant=libraryCatalogue?.variants.find(v=>v.id===content.variantId),choice=variant?.choices.find(c=>c.familyId===content.familyId&&c.modeIds.includes(content.modeId)),capabilities=choice?.capabilities;
 if(choice?.runtimeAvailable&&capabilities?.construction.kind==='fixed'&&capabilities.operation.kind==='rotation'&&capabilities.presentation.kind==='detailed-carousel'){selectedRideContent={...content};setTool('track');subtool='create-ride';contentLibrary.close();renderPalette();$('new-ride-name').value=variant.label;}
 else if(choice?.runtimeAvailable&&capabilities?.construction.kind==='tracked'&&capabilities.operation.kind==='circuit'&&['procedural-coaster','detailed-wooden-coaster'].includes(capabilities.presentation.kind)){selectedRideContent={...content};setTool('track');subtool='create-ride';contentLibrary.close();renderPalette();$('new-ride-name').value=variant.label;}
 else if(capabilities?.construction.kind==='facility'&&capabilities.operation.kind==='service'&&capabilities.presentation.kind==='procedural-facility'){const kind=capabilities.construction.service;if(!Object.hasOwn(selectedFacilityContent,kind))return;selectedFacilityContent[kind]={...content};setTool('facility');subtool=kind;contentLibrary.close();renderPalette();}
 else{feedback('This content is not available for construction.',true);return;}
 schedulePreview();feedback('Content selected. Click the park to place it.');
}});
$('content-library').onclick=()=>contentLibrary.open({opener:$('content-library')});
const feedback=(message,error=false)=>{$('feedback').textContent=message;$('feedback').classList.toggle('error',error);$('feedback').classList.remove('hidden');};
scene.onAssetError=message=>feedback(message,true);
function request(type,payload){return new Promise((resolve,reject)=>{const id=++serial,timer=setTimeout(()=>{pending.delete(id);reject(new Error('The park did not respond. Reload the page to recover your last save.'));},20000);pending.set(id,{resolve,reject,timer});worker.postMessage({id,protocolVersion:WORKER_PROTOCOL_VERSION,request:{type,payload}});});}
worker.onmessage=event=>{const m=event.data;if(m.protocolVersion!==WORKER_PROTOCOL_VERSION){const error=new Error('The park worker uses an unsupported protocol. Reload the page.');feedback(error.message,true);for(const p of pending.values()){clearTimeout(p.timer);p.reject(error);}pending.clear();return;}if(m.event==='ready'){restoreLocal();return;}if(m.event==='error'){feedback(m.error.message,true);return;}const call=pending.get(m.id);if(!call)return;clearTimeout(call.timer);pending.delete(m.id);if(m.result.ok)call.resolve(m.result.value);else call.reject(new Error(m.result.error.message));};
worker.onerror=event=>{feedback('The park could not start: '+event.message,true);for(const p of pending.values()){clearTimeout(p.timer);p.reject(new Error(event.message));}pending.clear();};
async function execute(command){try{const quote=await request('quote',command),receipt=await request('execute',{command,revision:quote.revision});staticRevision=null;inspectSignature='';quoted=null;if(command.type==='create-ride'){selectedRide=receipt.id;selection={kind:'ride',id:receipt.id};subtool=command.content?.familyId==='independent.carousel'?'entrance':'station';renderPalette();}feedback(receipt.cost?`${receipt.cost>0?'Built for':'Refund received'} ${money(Math.abs(receipt.cost))}.`:'Park updated.');await refresh(true);return receipt;}catch(e){feedback(e.message,true);return null;}}
function editPatrol(tile=null,staff=selection?.kind==='staff'?selection.id:null){
 const point=tile?{...tile}:null;if(staff===null)return patrolUpdate;
 patrolUpdate=patrolUpdate.then(async()=>{if(selection?.kind!=='staff'||selection.id!==staff)return;const tiles=point?(patrolTiles.some(t=>t.x===point.x&&t.y===point.y)?patrolTiles.filter(t=>t.x!==point.x||t.y!==point.y):[...patrolTiles,point]):[];if(await execute({type:'set-staff-patrol',staff,tiles})){if(selection?.kind==='staff'&&selection.id===staff)patrolTiles=tiles;}});return patrolUpdate;
}
async function refresh(force=false){if(force){staticRequested=true;staticEpoch++;}if(!ready||requesting)return;requesting=true;const requestedEpoch=staticEpoch;try{const size=packet?.side??48,next=await request('view',{bounds:{x0:0,y0:0,x1:Math.min(size-1,63),y1:Math.min(size-1,63)},includeStatic:staticRequested||staticRevision===null});packet=next;if(next.scenery&&requestedEpoch===staticEpoch){staticRevision=next.commandRevision;staticRequested=false;}scene.update(next);if(next.scenery&&(tool==='track'||tool==='path'))renderPalette();updateDesk();if(performance.now()-lastInspect>400||force){lastInspect=performance.now();await renderInspection();}}catch(e){feedback(e.message,true);}finally{requesting=false;}}
setInterval(()=>refresh(),50);
function updateDesk(){const s=packet;$('cash').textContent=money(s.cash);$('finance').classList.toggle('debt',s.cash<0);$('guest-count').textContent=`${s.counts.guests} guests`;$('pause').textContent=s.paused?'▶':'Ⅱ';$('park-toggle').textContent=s.parkOpen?'Park open':'Park closed';$('park-toggle').classList.toggle('closed',!s.parkOpen);const months=['March','April','May','June','July','August','September','October'],month=Math.floor(s.tick/16384);$('calendar').textContent=`${months[month%8]} · Year ${1+Math.floor(month/8)}`;$('scene-status').textContent=`${s.counts.guests} guests · ${s.counts.staff} staff`;
 const dropdown=$('ride-select');if(dropdown&&[...dropdown.options].map(o=>Number(o.value)).join(',')!==s.rides.map(r=>r.id).join(',')){dropdown.replaceChildren(...s.rides.map(r=>{const option=new Option(r.name,r.id);return option;}));dropdown.value=selectedRide;}
}
const help={inspect:['Park inspector','Select a ride, guest or staff member.'],track:['Ride construction','Choose a ride, then build its entrances or track.'],path:['Paths & queues','Click land to lay a connected path.'],facility:['Shops & facilities','Place a shop beside a public path.'],amenity:['Benches & bins','Click a public path to attach an amenity.'],staff:['Park staff','Place staff on a public path.'],terrain:['Land & water','Click land to change its height or water.'],scenery:['Scenery & gardens','Plant trees, add flower beds and build park details.'],patrol:['Staff patrol','Click owned tiles to paint this employee’s area.']};
function setTool(next){tool=next;subtool=next==='track'?(packet?.rides.find(r=>r.id===selectedRide)?.presentation.kind==='detailed-carousel'?'entrance':'flat'):next==='path'?'public':next==='facility'?'food':next==='amenity'?'bench':next==='staff'?'mechanic':next==='terrain'?'terrain':next==='scenery'?'tree':next;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===next));$('tool-label').textContent=help[next][0];$('tool-help').textContent=help[next][1];scene.ghost.clear();renderPalette();schedulePreview();}
function renderPalette(){let html='';const ride=packet?.rides.find(r=>r.id===selectedRide),pieces=ride?.trackProfile?.pieces??steelRules.pieces;const choices=(values)=>values.filter(([value])=>tool!=='track'||Object.hasOwn(pieces,value)).map(([value,label])=>`<button data-sub="${value}" class="${value===subtool?'selected':''}">${label}</button>`).join('');const rideDropdown=()=>`<select id="ride-select" aria-label="Selected coaster">${(packet?.rides??[]).map(r=>`<option value="${r.id}" ${r.id===selectedRide?'selected':''}>${escape(r.name)}</option>`).join('')}</select>`;
 if(tool==='inspect')html='<span class="muted">Click a guest to inspect their needs. Select a coaster to test, open or close it.</span>';
 if(tool==='track')html=rideDropdown()+'<button id="new-coaster">New coaster</button>'+choices([['station','Station'],['flat','Straight'],['left','Left turn'],['right','Right turn'],['brake','Brakes']])+`<select id="advanced-piece" aria-label="More track pieces"><option value="">More pieces…</option>${['lift-start','lift','lift-end','drop-start','drop','drop-end','bank-start','banked','bank-end'].filter(p=>Object.hasOwn(pieces,p)).map(p=>`<option value="${p}" ${p===subtool?'selected':''}>${p.replaceAll('-',' ')}</option>`).join('')}</select><button id="build-track">Build</button><button id="remove-track">Remove last</button><button data-sub="entrance">Entrance</button><button data-sub="exit">Exit</button>`;
 if(tool==='track'&&ride?.presentation.kind==='detailed-carousel')html=rideDropdown()+'<button id="new-coaster">New ride</button><button data-sub="entrance">Entrance</button><button data-sub="exit">Exit</button><span class="muted">Place portals at the marked body sockets, then connect queue and public paths.</span>';
 if(tool==='path')html=choices([['public','Public path'],['queue','Queue path'],['park-entry','Park entrance']])+rideDropdown();
 if(tool==='facility')html=choices([['food','Food stand'],['drink','Drink stand'],['restroom','Restroom']]);
 if(tool==='amenity')html=choices([['bench','Bench'],['bin','Litter bin']]);
 if(tool==='staff')html=choices([['mechanic','Mechanic'],['handyman','Handyman']]);
 if(tool==='scenery')html=choices([['tree','Trees'],['flower','Flower bed'],['hedge','Hedge'],['lamp','Lantern'],['fountain','Fountain'],['rock','Rock garden']]);
 if(tool==='terrain')html='<label>Ground <input id="ground" type="number" step="16" min="0" max="256" value="32"></label><label>Water <input id="water" type="number" step="16" min="0" max="256" value="0"></label><span class="muted">Water 0 clears the tile.</span>';
 if(tool==='patrol')html='<button id="patrol-all">Full park</button><span class="muted">Green tiles are in this employee’s patrol. Click again to remove a tile.</span>';
 if(tool==='track'&&(subtool==='entrance'||subtool==='exit'))html=rideDropdown()+`<button data-sub="entrance" class="${subtool==='entrance'?'selected':''}">Entrance</button><button data-sub="exit" class="${subtool==='exit'?'selected':''}">Exit</button><select id="station-select" aria-label="Station section">${(scene.elements??[]).filter(e=>e.ride===selectedRide&&(e.kind==='fixed-body'||e.kind==='track'&&pieces[e.piece]?.station)).map(e=>`<option value="${e.id}">Station section ${e.id}</option>`).join('')}</select>`;
 if(tool==='track'&&subtool==='create-ride')html='<label>Ride name <input id="new-ride-name" value="New ride" maxlength="80"></label><span class="muted">Click land to place the selected ride.</span>';
 $('palette').innerHTML=html;document.querySelectorAll('[data-sub]').forEach(b=>b.onclick=()=>{subtool=b.dataset.sub;renderPalette();schedulePreview();});if($('ride-select'))$('ride-select').onchange=e=>{selectedRide=Number(e.target.value);if(tool==='track'&&packet?.rides.find(r=>r.id===selectedRide)?.presentation.kind==='detailed-carousel'&&subtool!=='exit')subtool='entrance';selection={kind:'ride',id:selectedRide};inspectSignature='';renderPalette();schedulePreview();};if($('advanced-piece'))$('advanced-piece').onchange=e=>{if(e.target.value){subtool=e.target.value;renderPalette();schedulePreview();}};if($('new-coaster'))$('new-coaster').onclick=()=>{subtool='create-ride';renderPalette();scene.ghost.clear();};if($('build-track'))$('build-track').onclick=()=>{const c=commandAt(hover);if(c)execute(c);};if($('remove-track'))$('remove-track').onclick=()=>execute({type:'remove-last-track',ride:selectedRide});if($('patrol-all'))$('patrol-all').onclick=()=>editPatrol();
}
function commandAt(point){const height=Number($('height').value),direction=Number($('direction').value),path=point&&(scene.elements??[]).find(e=>e.kind==='path'&&e.tile.x===point.x&&e.tile.y===point.y&&e.height===height);
 if(tool==='track'&&subtool!=='create-ride'&&subtool!=='entrance'&&subtool!=='exit')return{type:'append-track',ride:selectedRide,piece:subtool};
 if(!point||point.x<0||point.y<0||point.x>255||point.y>255)return null;
 if(tool==='track'&&subtool==='create-ride')return{type:'create-ride',name:$('new-ride-name').value.trim()||'New coaster',tile:point,height,direction,content:{...selectedRideContent}};
 if(tool==='track'&&(subtool==='entrance'||subtool==='exit'))return{type:'place-portal',ride:selectedRide,station:Number($('station-select')?.value),role:subtool,tile:point,height,direction};
 if(tool==='path'){if(subtool==='park-entry')return{type:'set-park-entrance',point:{...point,z:height}};return{type:'place-path',tile:point,height,queueFor:subtool==='queue'?selectedRide:null};}
 if(tool==='facility')return{type:'place-facility',name:subtool==='food'?'Food stand':subtool==='drink'?'Drink stand':'Restrooms',kind:subtool,tile:point,height,direction,content:{...selectedFacilityContent[subtool]}};
 if(tool==='amenity')return path?{type:'place-amenity',kind:subtool,path:path.id}:null;
 if(tool==='staff')return{type:'hire-staff',role:subtool,point:{...point,z:height}};
 if(tool==='scenery')return{type:'place-scenery',sceneryType:subtool,tile:point,height};
 if(tool==='terrain')return{type:'set-terrain',tile:point,height:Number($('ground').value),water:Number($('water').value)};
 return null;
}
function schedulePreview(){clearTimeout(previewTimer);previewTimer=setTimeout(async()=>{const c=commandAt(hover),generation=++quoteSequence;if(!c||tool==='inspect'||tool==='patrol'){scene.ghost.clear();return;}try{const q=await request('quote',c);if(generation!==quoteSequence)return;quoted={command:c,quote:q};const cells=q.cells.length?q.cells:hover?[{...hover,low:Number($('height').value)}]:[];scene.preview(cells,true);if($('build-track')){$('build-track').disabled=false;$('build-track').textContent='Build '+money(q.cost);}if(hover)$('position').textContent=`Tile ${hover.x}, ${hover.y} · ${money(q.cost)}`;}catch(e){if(generation!==quoteSequence)return;quoted=null;const ride=packet?.rides.find(r=>r.id===selectedRide),anchor=ride?.tip??ride?.anchor,point=hover??(anchor?{x:anchor.x/32,y:anchor.y/32}:null);scene.preview(point?[{...point,low:Number($('height').value)}]:[],false);if($('build-track'))$('build-track').disabled=true;$('position').textContent=e.message;}},70);}
$('height').oninput=schedulePreview;$('direction').onchange=schedulePreview;
let down=null;$('viewport').addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};});$('viewport').addEventListener('pointermove',e=>{hover=scene.pointer(e,Number($('height').value));if(tool!=='inspect')schedulePreview();});$('viewport').addEventListener('pointerup',async e=>{if(e.button!==0||!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)return;hover=scene.pointer(e,Number($('height').value));if(tool==='inspect'){select(scene.pick(e));return;}if(tool==='patrol'&&selection?.kind==='staff'&&hover){await editPatrol(hover);return;}const c=commandAt(hover);if(c)await execute(c);else feedback('Choose a public path at the selected height.',true);schedulePreview();});
function select(value){selection=value;inspectSignature='';if(value?.kind==='element'){const e=scene.elements.find(e=>e.id===value.id);if(e?.kind==='track'||e?.kind==='fixed-body'){selection={kind:'ride',id:e.ride};selectedRide=e.ride;}else if(e?.kind==='facility')selection={kind:'facility',id:e.facility};}if(selection?.kind==='ride')selectedRide=selection.id;renderInspection();}
const stat=(label,value)=>`<div class="stat"><small>${escape(label)}</small><strong>${escape(value)}</strong></div>`,row=(label,value)=>`<div class="row"><span>${escape(label)}</span><strong>${escape(value)}</strong></div>`;
async function renderInspection(){if(!packet)return;const expectedSelection=selection?{...selection}:null;if($('inspection').contains(document.activeElement)&&['INPUT','SELECT'].includes(document.activeElement.tagName))return;let html='',title='Park overview',data=null;try{
 if(!selection){html=`<p class="lead">Copper Meadows</p><p class="muted">A park of your own. Build connected paths, test your coasters and keep your guests happy.</p><div class="stats">${stat('Guests',packet.counts.guests)}${stat('Staff',packet.counts.staff)}${stat('Coasters',packet.rides.length)}${stat('Ground litter',packet.counts.litter)}</div><p class="section-label">Coasters</p>`+packet.rides.map(r=>`<button class="ride-card" data-select-ride="${r.id}"><strong>${escape(r.name)}</strong><small>${escape(r.status)} · ${r.queue} waiting · ${money(r.income)} ticket sales</small></button>`).join('')+'<p class="section-label">Facilities</p>'+packet.facilities.map(f=>`<button class="ride-card" data-select-facility="${f.id}"><strong>${escape(f.name)}</strong><small>${f.open?'Open':'Closed'} · ${money(f.income)} sales</small></button>`).join('')+'<p class="section-label">Park staff</p>'+packet.staff.map(t=>`<button class="ride-card" data-select-staff="${t.id}"><strong>${t.role==='mechanic'?'Mechanic':'Handyman'} ${t.id}</strong><small>${t.work??'Available'} · ${t.completed} completed jobs</small></button>`).join('');}
 else if(selection.kind==='ride'){data=packet.rides.find(r=>r.id===selection.id);if(!data){selection=null;return;}title=data.presentation.kind==='detailed-carousel'?'Carousel':'Coaster';if(data.presentation.kind==='detailed-carousel'){const session=packet.carouselSessions.find(s=>s.ride===data.id),owners=session?.seatIds??Array(16).fill(null);html=`<p class="lead">${escape(data.name)}</p><p class="muted">${data.broken?'Broken down · Waiting for a mechanic':escape(data.status)} · ${escape(data.sessionPhase)} · ${data.queue} in queue</p><div class="stats">${stat('Riders',owners.filter(id=>id!==null).length+' / 16')}${stat('Ticket sales',money(data.income))}${stat('Completed cycles',session?.completedCycles??0)}${stat('Cycle','26 seconds')}</div><div class="actions"><button id="ride-test">Test</button><button id="ride-open">Open</button><button id="ride-close">Close</button></div><div class="inspection-form"><label for="ride-price">Ticket</label><input id="ride-price" type="number" value="${data.price/10}" min="0" max="10" step=".1"><button id="price-apply">Set</button></div><p class="section-label">Passenger seats</p><div class="carousel-seat-grid">${owners.map((id,slot)=>`<button ${id===null?'disabled':`data-carousel-guest="${id}"`} title="Seat ${slot+1}${id===null?' · Empty':' · Guest '+id}">${slot+1}${id===null?'':' ●'}</button>`).join('')}</div><div class="actions"><button id="edit-ride">Edit entrances</button><button id="ride-remove" class="danger">Demolish</button></div>`;}else{const m=data.measured;html=`<p class="lead">${escape(data.name)}</p><p class="muted">${data.broken?'Broken down · Waiting for a mechanic':data.status==='closed'&&data.trainPhase==='running'?'Closed · Train returning':escape(data.status)} · ${data.queue} in queue</p><div class="stats">${stat('Ticket sales',money(data.income))}${stat('Track pieces',data.trackCount)}</div><div class="actions"><button id="ride-test">Test</button><button id="ride-open">Open</button><button id="ride-close">Close</button></div><div class="inspection-form"><label for="ride-price">Ticket</label><input id="ride-price" type="number" value="${data.price/10}" min="0" max="100" step=".1"><button id="price-apply">Set</button></div><div class="inspection-form"><label for="car-count">Cars</label><input id="car-count" type="number" value="${data.cars}" min="1" max="${data.trackProfile?.motion.maxCars??steelRules.motion.maxCars}" step="1"><button id="cars-apply">Set</button></div><button id="edit-ride">Build / edit track</button><p class="section-label">Test measurements</p>`+(m?row('Length',(m.distance/1000).toFixed(1)+' m')+row('Max speed',(m.maxSpeed*40/1000*3.6).toFixed(1)+' km/h')+row('Duration',(m.ticks/40).toFixed(1)+' s')+row('Vertical forces',(m.minVerticalG/1000).toFixed(2)+' to '+(m.maxVerticalG/1000).toFixed(2)+' g')+row('Lateral force',(m.maxLateralG/1000).toFixed(2)+' g'):'<p class="muted">Complete a test circuit to record measurements.</p>');}}
 else if(selection.kind==='facility'){data=packet.facilities.find(f=>f.id===selection.id);if(!data){selection=null;return;}title='Facility';html=`<p class="lead">${escape(data.name)}</p><p class="muted">${escape(data.kind)} · ${data.open?'Open':'Closed'}</p><div class="stats">${stat('Sales',data.sales)}${stat('Revenue',money(data.income))}</div><div class="inspection-form"><label>Price</label><input id="facility-price" type="number" value="${data.price/10}" min="0" max="100" step=".1"><button id="facility-price-apply">Set</button></div><div class="actions"><button id="facility-toggle">${data.open?'Close':'Open'}</button><button id="facility-remove" class="danger">Demolish</button></div><p class="muted">The counter must face a connected public path.</p>`;}
 else{data=await request('inspect',{kind:selection.kind,id:selection.id});if(selection?.kind!==expectedSelection.kind||selection?.id!==expectedSelection.id)return;if(selection.kind==='guest'){title='Guest';html=`<p class="lead">Guest ${data.id}</p><p class="muted">${escape(data.phase)} · ${escape(data.thought.replaceAll('-',' '))}</p>`+row('Cash',money(data.cash))+row('Spent',money(data.spent))+row('Completed rides',data.ridesTaken)+['hunger','thirst','bladder','nausea','happiness','energy'].map(k=>`<div class="need"><div class="need-label"><span>${k[0].toUpperCase()+k.slice(1)}</span><span>${Math.round(data[k]/10)}%</span></div><div class="bar ${['hunger','thirst','bladder','nausea'].includes(k)&&data[k]>650?'warning':''}"><span style="width:${data[k]/10}%"></span></div></div>`).join('');scene.highlight(data.point);}
 else if(selection.kind==='staff'){title='Staff';html=`<p class="lead">${data.role==='mechanic'?'Mechanic':'Handyman'} ${data.id}</p>`+row('Current work',data.job?.kind??data.cleanup?.kind??'Available')+row('Completed jobs',data.completed)+row('Patrol',data.patrol.length?'Assigned area':'Full park')+'<div class="actions"><button id="staff-patrol">Paint patrol</button><button id="staff-all">Full park</button><button id="staff-fire" class="danger">Dismiss</button></div><p class="muted">Work must be reachable inside the patrol area.</p>';scene.highlight(data.point);}
 else{const e=data;title=e.kind==='scenery'?({tree:'Tree',flower:'Flower bed',hedge:'Hedge',lamp:'Park lantern',fountain:'Fountain',rock:'Rock garden'}[e.sceneryType]):e.kind==='amenity'?e.amenityType==='bench'?'Bench':'Litter bin':e.kind==='portal'?e.role==='entrance'?'Ride entrance':'Ride exit':'Path';html=`<p class="lead">${title}</p>`+row('Tile',e.tile.x+', '+e.tile.y)+row('Height',e.height)+(e.kind==='amenity'?(()=>{const a=packet.amenities.find(a=>a.id===e.id);return a.kind==='bench'?row('Occupant',a.occupant??'Empty'):row('Fill',a.fill+' / '+steelRules.housekeeping.binCapacity);})():'')+'<div class="actions"><button id="element-remove" class="danger">Remove</button></div>';scene.highlight({...e.tile,z:e.height});}}
 const signature=JSON.stringify([selection,html]);if(signature===inspectSignature)return;inspectSignature=signature;$('inspector-title').textContent=title;$('inspection').innerHTML=html;
 document.querySelectorAll('[data-select-ride]').forEach(b=>b.onclick=()=>select({kind:'ride',id:Number(b.dataset.selectRide)}));document.querySelectorAll('[data-select-staff]').forEach(b=>b.onclick=()=>select({kind:'staff',id:Number(b.dataset.selectStaff)}));document.querySelectorAll('[data-select-facility]').forEach(b=>b.onclick=()=>select({kind:'facility',id:Number(b.dataset.selectFacility)}));
 if(selection?.kind==='ride'){for(const [button,status] of [['ride-test','testing'],['ride-open','open'],['ride-close','closed']])$(button).onclick=()=>execute({type:'set-ride-status',ride:expectedSelection.id,status});$('price-apply').onclick=()=>execute({type:'set-ride-price',ride:expectedSelection.id,price:Math.round(Number($('ride-price').value)*10)});if($('cars-apply'))$('cars-apply').onclick=()=>execute({type:'set-train-cars',ride:expectedSelection.id,cars:Number($('car-count').value)});if($('ride-remove'))$('ride-remove').onclick=async()=>{if(await execute({type:'remove-ride',ride:expectedSelection.id}))select(null);};$('edit-ride').onclick=()=>{selectedRide=expectedSelection.id;setTool('track');if(data.presentation.kind==='detailed-carousel'){subtool='entrance';renderPalette();}};document.querySelectorAll('[data-carousel-guest]').forEach(button=>button.onclick=()=>select({kind:'guest',id:Number(button.dataset.carouselGuest)}));}
 if(selection?.kind==='facility'){$('facility-toggle').onclick=()=>execute({type:'set-facility-open',facility:expectedSelection.id,open:!data.open});$('facility-price-apply').onclick=()=>execute({type:'set-facility-price',facility:expectedSelection.id,price:Math.round(Number($('facility-price').value)*10)});$('facility-remove').onclick=async()=>{if(await execute({type:'remove-facility',facility:expectedSelection.id}))select(null);};}
 if(selection?.kind==='staff'){$('staff-fire').onclick=async()=>{if(await execute({type:'fire-staff',staff:expectedSelection.id}))select(null);};$('staff-all').onclick=()=>editPatrol(null,expectedSelection.id);$('staff-patrol').onclick=()=>{patrolTiles=[];for(let bit=0;bit<65536;bit++)if(data.patrol.length&&(data.patrol[bit>>>5]&(1<<(bit&31))))patrolTiles.push({x:bit%256,y:Math.floor(bit/256)});setTool('patrol');};}
 if(selection?.kind==='element')$('element-remove').onclick=async()=>{const type=data.kind==='path'?'remove-path':data.kind==='amenity'?'remove-amenity':data.kind==='scenery'?'remove-scenery':'remove-portal';if(await execute({type,id:expectedSelection.id}))select(null);};
 }catch(e){feedback(e.message,true);selection=null;inspectSignature='';}}
$('clear-selection').onclick=()=>{scene.highlight(null);select(null);};document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$('camera').onclick=()=>scene.overview();$('close-camera').onclick=()=>scene.close();$('pause').onclick=()=>packet&&execute({type:'set-paused',paused:!packet.paused});$('park-toggle').onclick=()=>packet&&execute({type:'set-park-open',open:!packet.parkOpen});document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=async()=>{try{await request('speed',Number(b.dataset.speed));document.querySelectorAll('[data-speed]').forEach(button=>button.classList.toggle('active',button===b));}catch(e){feedback(e.message,true);}});
document.addEventListener('keydown',e=>{if(document.activeElement.closest('dialog')||(e.code==='Space'&&document.activeElement.tagName==='BUTTON'))return;if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();$('pause').click();}if(e.key==='Escape'){setTool('inspect');select(null);}if(e.key.toLowerCase()==='q'||e.key.toLowerCase()==='e'){const step=e.key.toLowerCase()==='q'?-1:1;$('direction').value=(Number($('direction').value)+step+4)%4;schedulePreview();}});
$('finance').onclick=()=>{if(!packet)return;const l=packet.ledger;$('finance-summary').innerHTML=`<p class="lead">${money(packet.cash)}</p><table class="finance-table"><tr><td>Ticket sales</td><td>${money(l.rideSales)}</td></tr><tr><td>Shop sales</td><td>${money(l.shopSales)}</td></tr>${[['Stock cost',l.stock],['Wages',l.wages],['Upkeep',l.upkeep],['Interest',l.interest]].map(([label,n])=>`<tr><td>${label}</td><td class="expense">− ${money(n)}</td></tr>`).join('')}<tr class="total"><td>Operating balance</td><td>${money(l.rideSales+l.shopSales-l.stock-l.wages-l.upkeep-l.interest)}</td></tr></table>`;$('loan').value=packet.loan/10;$('loan').max=packet.maxLoan/10;$('loan-feedback').textContent='Maximum loan '+money(packet.maxLoan);$('finance-dialog').showModal();};$('set-loan').onclick=async()=>{const receipt=await execute({type:'set-loan',amount:Math.round(Number($('loan').value)*10)});$('loan-feedback').textContent=receipt?'Loan updated.':'Unable to update loan. See the park message.';};
function db(){return new Promise((resolve,reject)=>{const req=indexedDB.open('coaster-tycoon-3d',1);req.onupgradeneeded=()=>req.result.createObjectStore('parks');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function saveLocal(quiet=false){if(quiet&&!localSaveAllowed)return;try{const save=await request('save',null),database=await db();await new Promise((resolve,reject)=>{const tx=database.transaction('parks','readwrite');tx.objectStore('parks').put(save,saveSlot);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});database.close();localSaveAllowed=true;$('save-status').textContent='Saved '+new Date().toLocaleTimeString('en',{hour:'2-digit',minute:'2-digit'});if(!quiet)feedback('Your park has been saved in this browser.');}catch(e){feedback('Save failed: '+e.message,true);}}
async function restoreLocal(){try{const database=await db(),save=await new Promise((resolve,reject)=>{const store=database.transaction('parks').objectStore('parks'),r=store.get(saveSlot);r.onsuccess=()=>{if(r.result!==undefined){resolve(r.result);return;}const previous=store.get(previousSaveSlot);previous.onsuccess=()=>{if(previous.result!==undefined){resolve(previous.result);return;}const legacy=store.get(legacySaveSlot);legacy.onsuccess=()=>resolve(legacy.result);legacy.onerror=()=>reject(legacy.error);};previous.onerror=()=>reject(previous.error);};r.onerror=()=>reject(r.error);});database.close();if(save!==undefined){await request('load',save);staticRevision=null;feedback('Your saved park has been restored.');}}catch(e){localSaveAllowed=false;feedback('Saved park was not loaded: '+e.message,true);}finally{ready=true;await refresh(true);renderPalette();document.body.inert=false;if(!document.getElementById('feedback').classList.contains('error'))feedback('Your park is ready. Select a tool to build or inspect.');}}
$('save').onclick=()=>saveLocal();setInterval(()=>{if(ready)saveLocal(true);},60000);$('export').onclick=async()=>{try{const save=await request('save',null),url=URL.createObjectURL(new Blob([save],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='coaster-park.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);feedback('Park exported. Keep the file as a backup of this park.');}catch(e){feedback(e.message,true);}};$('import').onclick=()=>$('import-file').click();$('import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>64*1024*1024)throw new Error('This park file is too large.');await request('load',await file.text());selection=null;inspectSignature='';staticRevision=null;await refresh(true);feedback('Park imported successfully.');}catch(error){feedback('Import failed: '+error.message,true);}finally{e.target.value='';}};$('new').onclick=async()=>{if(!confirm('Start a new Copper Meadows park? Save or export this park first if you want to keep it.'))return;try{await request('new-park',null);localSaveAllowed=true;scene.requestOverview();selection=null;staticRevision=null;inspectSignature='';await refresh(true);renderPalette();feedback('A new park is ready.');}catch(e){feedback(e.message,true);}};
renderPalette();

export {request,execute,scene,refresh,contentLibrary};
