import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const root='/workspace/coaster-wooden-hitch-authoring';
if(process.platform!=='linux')throw new Error('Remote only');
const sha=b=>createHash('sha256').update(b).digest('hex');
const files={original:'/workspace/coaster-detailed-assets/outputs/wooden-car.glb',candidate:root+'/outputs/wooden-car-joint.glb'};
const hashes={original:'fc988c55ed60dcd5abf7c5e02ecbc1ac3a8cd828cfe7fe4bb8f30bcf21699b59',candidate:'8eb82e43eac118cbeb652f70755110215b1168202adb8ef28747e1fccc3093ce'};
function decode(bytes){let g,bin;for(let at=12;at<bytes.length;){const n=bytes.readUInt32LE(at),type=bytes.readUInt32LE(at+4),data=bytes.subarray(at+8,at+8+n);if(type===0x4e4f534a)g=JSON.parse(data);if(type===0x004e4942)bin=data;at+=8+n;}
function accessor(index){const a=g.accessors[index],v=g.bufferViews[a.bufferView],dim={SCALAR:1,VEC2:2,VEC3:3,VEC4:4}[a.type],size={5123:2,5125:4,5126:4}[a.componentType],reader={5123:'readUInt16LE',5125:'readUInt32LE',5126:'readFloatLE'}[a.componentType];if(!dim||!size||a.sparse)throw new Error('Unsupported diagnostic accessor');return{descriptor:{type:a.type,componentType:a.componentType,normalized:a.normalized??false},values:Array.from({length:a.count},(_,i)=>Array.from({length:dim},(_,j)=>bin[reader]((v.byteOffset??0)+(a.byteOffset??0)+i*(v.byteStride??size*dim)+j*size)))};}
const meshes={};for(const node of g.nodes)if(node.mesh!==undefined){const layers={},triangles={},values={};let count=0;for(const p of g.meshes[node.mesh].primitives){const attrs=Object.fromEntries(Object.entries(p.attributes).map(([name,index])=>[name,accessor(index)])),indices=p.indices===undefined?Array.from({length:attrs.POSITION.values.length},(_,i)=>i):accessor(p.indices).values.flat();count+=indices.length/3;for(const [name,a]of Object.entries(attrs)){layers[name]??=a.descriptor;triangles[name]??=[];values[name]??=new Set();for(const value of a.values)values[name].add(JSON.stringify(value));for(let i=0;i<indices.length;i+=3){const ids=indices.slice(i,i+3),keys=ids.map(id=>JSON.stringify({position:attrs.POSITION.values[id],value:a.values[id]}));const key=[0,1,2].map(start=>[0,1,2].map(j=>keys[(start+j)%3]).join('|')).sort()[0];triangles[name].push(key);}}}meshes[node.name]={triangles:count,layers:Object.fromEntries(Object.keys(layers).map(name=>[name,{descriptor:layers[name],positionBoundTriangleSha256:sha(Buffer.from(triangles[name].sort().join('\n'))),uniqueEncodedValueSha256:sha(Buffer.from([...values[name]].sort().join('\n'))),uniqueEncodedValues:values[name].size}]))};}return meshes;}
const models={},provenance={};for(const [name,file]of Object.entries(files)){const bytes=await readFile(file);if(sha(bytes)!==hashes[name])throw new Error('Hash changed: '+name);models[name]=decode(bytes);provenance[name]={path:file,sha256:sha(bytes),bytes:bytes.length};}
const differences=[];for(const [name,original]of Object.entries(models.original)){if(name==='Chassis_Frame')continue;const candidate=models.candidate[name],names=[...new Set([...Object.keys(original.layers),...Object.keys(candidate.layers)])];differences.push({name,originalTriangles:original.triangles,candidateTriangles:candidate.triangles,layers:names.map(layer=>({name:layer,descriptorEqual:JSON.stringify(original.layers[layer]?.descriptor)===JSON.stringify(candidate.layers[layer]?.descriptor),triangleEqual:original.layers[layer]?.positionBoundTriangleSha256===candidate.layers[layer]?.positionBoundTriangleSha256,uniqueValuesEqual:original.layers[layer]?.uniqueEncodedValueSha256===candidate.layers[layer]?.uniqueEncodedValueSha256,original:original.layers[layer]??null,candidate:candidate.layers[layer]??null}))});}
const result={scope:'Read-only encoded attribute diagnostic for the rejected c75 candidate; no acceptance relaxation. Chassis omitted because its allowed index removal already passed the frozen checker.',provenance,runnerSha256:sha(await readFile(root+'/checks/attribute-diff.mjs')),differences};
const output=root+'/checks/attribute-diff-c75.json';await writeFile(output,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({output,resultSha256:sha(await readFile(output)),differences:differences.map(m=>({name:m.name,changedTriangles:m.layers.filter(l=>!l.triangleEqual).map(l=>l.name),changedUniqueValues:m.layers.filter(l=>!l.uniqueValuesEqual).map(l=>l.name)}))}));
