import type { Amenity, Litter, CleanupJob } from './housekeeping.js';
import { type Direction, type State, type Rules, type Tile } from './types.js';
import type { Guest, PathPoint, PeopleIndex, Routing } from './people.js';
import type { ContentIdentity } from '../content/registry.js';
export type FacilityKind = 'food' | 'drink' | 'restroom';
export type Facility = {
    id: number;
    instanceId: number;
    content: ContentIdentity;
    name: string;
    kind: FacilityKind;
    element: number;
    open: boolean;
    price: number;
    income: number;
    sales: number;
};
export type FacilityElement = {
    id: number;
    kind: 'facility';
    facility: number;
    tile: Tile;
    height: number;
    direction: Direction;
};
export type Staff = {
    id: number;
    role: 'mechanic' | 'handyman';
    point: PathPoint;
    next: PathPoint | null;
    goal: PathPoint | null;
    progress: number;
    patrol: number[];
    job: {
        ride: number;
        kind: 'repair' | 'inspection';
    } | null;
    work: number;
    completed: number;
    cleanup: CleanupJob | null;
};
export type ServiceRules = {
    buildPrice: number;
    defaultPrice: number;
    maxPrice: number;
    foodStock: number;
    drinkStock: number;
    needThreshold: number;
    relief: number;
    initialBladder: number;
    serviceTicks: number;
    weekTicks: number;
    upkeepWeeks: number;
    mechanicMonthlyWage: number;
    handymanMonthlyWage: number;
    rideUpkeep: number;
    facilityUpkeep: number;
    interestPer10000: number;
    staffWalkTicks: number;
    repairTicks: number;
    inspectionTicks: number;
    inspectionInterval: number;
};
export type ServiceIndex = PeopleIndex & {
    amenities: Map<number, Amenity>;
    litter: Map<number, Litter>;
    facilities: Map<number, Facility>;
    staff: Map<number, Staff>;
};
export declare function validateServiceRules(input: ServiceRules): ServiceRules;
export declare function facilityApproach(e: FacilityElement): PathPoint;
export declare function sharedCount(s: State): number;
export declare function chooseFacility(g: Guest, s: State, rules: Rules, index: ServiceIndex, route: Routing): {
    facility: number;
    goal: PathPoint;
} | null;
export declare function recoverFacility(g: Guest, index: ServiceIndex): boolean;
export declare function buy(g: Guest, s: State, rules: Rules, index: ServiceIndex): void;
export declare function accessible(staff: Staff, goal: PathPoint, index: PeopleIndex, route: Routing): boolean;
export declare function recoverStaff(s: State, index: ServiceIndex, route: Routing): void;
export declare function stepStaff(s: State, rules: Rules, index: ServiceIndex, route: Routing): void;
export declare function stepFinance(s: State, rules: Rules): void;
