import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {steelRules} from './content/steel-coaster.js';
const tile=steelRules.motion.tileMetres,half=tile/2;
const rotate=(x,y,d)=>[[x,y],[-y,x],[-x,-y],[y,-x]][d];
const colors=['#d7b247','#bb6047','#83a56f','#4c7999','#b789a6','#e2dfcf'];
export class ParkScene{
 constructor(container){
  this.container=container;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#bad9cb');this.scene.fog=new THREE.Fog('#bad9cb',180,480);
  this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});this.renderer.setPixelRatio(1);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.setClearColor('#bad9cb');container.append(this.renderer.domElement);
  this.camera=new THREE.PerspectiveCamera(40,1,.1,650);this.camera.position.set(128,83,145);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.target.set(82,4,74);this.controls.enableDamping=true;this.controls.dampingFactor=.09;this.controls.maxPolarAngle=Math.PI/2.08;this.controls.minDistance=14;this.controls.maxDistance=340;
  this.scene.add(new THREE.HemisphereLight('#fff2d6','#68826b',2.3));const sun=new THREE.DirectionalLight('#fff5dd',3);sun.position.set(80,150,40);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-115;sun.shadow.camera.right=115;sun.shadow.camera.top=115;sun.shadow.camera.bottom=-115;sun.shadow.camera.near=1;sun.shadow.camera.far=330;sun.shadow.bias=-.0002;this.scene.add(sun);
  this.staticGroup=new THREE.Group();this.scene.add(this.staticGroup);this.staticGeometry=new Set();this.materials=new Map();this.box=new THREE.BoxGeometry(1,1,1);this.cylinder=new THREE.CylinderGeometry(1,1,1,8);this.sphere=new THREE.SphereGeometry(1,8,5);this.cone=new THREE.ConeGeometry(1,1,8);
  this.actorBodies=new THREE.InstancedMesh(this.cylinder,this.mat('#ffffff'),10000);this.actorHeads=new THREE.InstancedMesh(this.sphere,this.mat('#ebc19c'),10000);this.actorBodies.count=this.actorHeads.count=0;this.actorBodies.castShadow=true;this.actorBodies.frustumCulled=this.actorHeads.frustumCulled=false;this.scene.add(this.actorBodies,this.actorHeads);
  this.carBodies=new THREE.InstancedMesh(this.box,this.mat('#cc7437'),10000);this.carSeats=new THREE.InstancedMesh(this.box,this.mat('#355044'),10000);this.carHeads=new THREE.InstancedMesh(this.sphere,this.mat('#ebc19c'),10000);this.carBodies.count=this.carSeats.count=this.carHeads.count=0;this.carBodies.castShadow=true;this.carBodies.frustumCulled=this.carSeats.frustumCulled=this.carHeads.frustumCulled=false;this.scene.add(this.carBodies,this.carSeats,this.carHeads);
  this.litter=new THREE.InstancedMesh(this.box,this.mat('#f6e5cf'),10000);this.litter.count=0;this.litter.frustumCulled=false;this.scene.add(this.litter);
  this.ghost=new THREE.Group();this.scene.add(this.ghost);this.ghostMaterial=new THREE.MeshBasicMaterial({color:'#9fcc72',transparent:true,opacity:.45,depthWrite:false});this.selection=new THREE.Mesh(new THREE.BoxGeometry(4.08,.07,4.08),new THREE.MeshBasicMaterial({color:'#ecc25b',transparent:true,opacity:.55}));this.selection.visible=false;this.scene.add(this.selection);
  this.ray=new THREE.Raycaster();this.mouse=new THREE.Vector2();this.transform=new THREE.Object3D();this.actorIDs=[];this.carIDs=[];new ResizeObserver(()=>this.resize()).observe(container);this.resize();this.renderer.setAnimationLoop(()=>{this.controls.update();this.renderer.render(this.scene,this.camera);});
 }
 mat(color){if(!this.materials.has(color))this.materials.set(color,new THREE.MeshStandardMaterial({color,roughness:.83}));return this.materials.get(color);}
 block(parent,color,x,y,z,sx,sy,sz,kind='box'){const geo=kind==='cylinder'?this.cylinder:kind==='sphere'?this.sphere:kind==='cone'?this.cone:this.box,m=new THREE.Mesh(geo,this.mat(color));m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 resize(){const {clientWidth:w,clientHeight:h}=this.container;if(!w||!h)return;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false);}
 clearStatic(){this.staticGroup.clear();for(const geometry of this.staticGeometry)geometry.dispose();this.staticGeometry.clear();}
 setStatic(scenery,entry){
  this.clearStatic();this.elements=scenery.elements;
  const ground=new THREE.InstancedMesh(this.box,this.mat('#a8bc73'),scenery.surfaces.length/5);ground.receiveShadow=true;for(let i=0;i<scenery.surfaces.length;i+=5){const [x,y,height,water,owned]=scenery.surfaces.slice(i,i+5),h=height/32*tile;this.transform.position.set(x*tile+half,h/2,y*tile+half);this.transform.scale.set(tile,h,tile);this.transform.rotation.set(0,0,0);this.transform.updateMatrix();ground.setMatrixAt(i/5,this.transform.matrix);ground.setColorAt(i/5,new THREE.Color(owned?(x+y)%3===0?'#a8bc73':'#9eb16a':'#7d9a74'));if(water)this.block(this.staticGroup,'#78b6bc',x*tile+half,water/32*tile+.025,y*tile+half,tile,.04,tile);}
  ground.instanceMatrix.needsUpdate=true;ground.userData.ground=true;this.staticGroup.add(ground);
  for(const e of scenery.elements){const group=new THREE.Group();group.userData.selection={kind:'element',id:e.id};this.staticGroup.add(group);
   if(e.kind==='track')this.track(group,e);
   else{const x=e.tile.x*tile+half,z=e.tile.y*tile+half,h=e.height/32*tile;
    if(e.kind==='path'){this.block(group,e.queueFor===null?'#d2c6a6':'#809ab5',x,h+.08,z,3.85,.16,3.85);if(e.queueFor!==null){for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const adjacent=scenery.elements.some(p=>p.kind==='path'&&p.tile.x===e.tile.x+dx&&p.tile.y===e.tile.y+dy&&p.height===e.height&&(p.queueFor===null||p.queueFor===e.queueFor));if(!adjacent)this.block(group,'#f3e6c6',x+dx*1.7,h+.6,z+dy*1.7,dx?.08:3.8,1.15,dy?.08:3.8);}}if(h>4.05)this.block(group,'#85856d',x,h/2,z,.25,h,.25);}
    if(e.kind==='portal'){this.block(group,e.role==='entrance'?'#d7a13f':'#759b77',x,h+1.45,z,1.5,2.9,1.5);this.block(group,'#385d49',x,h+3.1,z,2.5,.35,2.5);this.block(group,'#fbedd0',x,h+1.3,z-.77,.7,1.65,.05);}
    if(e.kind==='facility'){const f=this.packet?.facilities.find(f=>f.id===e.facility),color=f?.kind==='food'?'#c56c4a':f?.kind==='drink'?'#6799a7':'#779e74';this.block(group,'#f1dfb9',x,h+1.45,z,3.35,2.9,3.35);this.block(group,color,x,h+3.15,z,3.75,.5,3.75);const [dx,dy]=rotate(1,0,e.direction);this.block(group,'#3b5148',x+dx*1.7,h+1.25,z+dy*1.7,dx? .04:1.65,1.55,dy?.04:1.65);const awning=this.block(group,color,x+dx*1.6,h+2.7,z+dy*1.6,dx?1.6:3.5,.2,dy?1.6:3.5);for(let j=-1;j<=1;j++)this.block(group,'#f3e3be',x+dx*1.6+(dy?j:.0),h+2.81,z+dy*1.6+(dx?j:0),dx?1.5:.45,.05,dy?1.5:.45);}
    if(e.kind==='amenity'){if(e.amenityType==='bench'){this.block(group,'#957044',x,h+.75,z+1.25,2.3,.18,.8);this.block(group,'#b1854a',x,h+1.15,z+1.6,2.3,.75,.15);for(const d of [-.8,.8])this.block(group,'#51644e',x+d,h+.38,z+1.25,.12,.75,.55);}else{this.block(group,'#536e5a',x+1.3,h+.6,z, .62,1.2,.62);this.block(group,'#edd5a0',x+1.3,h+1.24,z,.74,.12,.74);}}
   }
  }
  if(entry){const x=entry.x*tile+half,z=entry.y*tile+half,h=entry.z/32*tile;for(const off of [-2,2])this.block(this.staticGroup,'#eee2bb',x+off,h+2,z,.32,4,.32);this.block(this.staticGroup,'#345c49',x,h+4.1,z,4.5,.65,.5);}
  // Decorative trees stand on the unbuildable boundary, outside construction land.
  for(let i=2;i<46;i+=4){for(const [x,z] of [[i*tile,1],[1,i*tile]]){this.block(this.staticGroup,'#827157',x,3,z,.35,2,.35);this.block(this.staticGroup,'#608359',x,5,z,2.5,4,2.5,'cone');this.block(this.staticGroup,'#6e8e5b',x,6.5,z,1.9,3,1.9,'cone');}}
 }
 track(group,e){
  const p=steelRules.pieces[e.piece],points=p.motion.samples.map(v=>{const [x,z]=rotate(v.x,v.y,e.origin.direction);return new THREE.Vector3((e.origin.x+x)/32*tile+half,(e.origin.z+v.z)/32*tile+.3,(e.origin.y+z)/32*tile+half);});
  for(const side of [-1,1]){const rails=points.map((v,i)=>{const before=points[Math.max(0,i-1)],after=points[Math.min(points.length-1,i+1)],direction=after.clone().sub(before).normalize(),normal=new THREE.Vector3(-direction.z,0,direction.x).normalize(),bank=(p.entry.bank+(p.end.bank-p.entry.bank)*i/(points.length-1))*steelRules.motion.bankDegrees*Math.PI/180;return v.clone().addScaledVector(normal,side*.55*Math.cos(bank)).add(new THREE.Vector3(0,side*.55*Math.sin(bank),0));});const path=new THREE.CurvePath();for(let i=1;i<rails.length;i++)path.add(new THREE.LineCurve3(rails[i-1],rails[i]));const geometry=new THREE.TubeGeometry(path,Math.max(12,points.length*2),.07,5,false);this.staticGeometry.add(geometry);const mesh=new THREE.Mesh(geometry,this.mat('#cf9b45'));mesh.castShadow=true;group.add(mesh);}
  for(let i=0;i<points.length;i+=Math.max(1,Math.floor(points.length/6))){const v=points[i],next=points[Math.min(i+1,points.length-1)],direction=next.clone().sub(points[Math.max(0,i-1)]);const tie=this.block(group,'#5d6658',v.x,v.y-.08,v.z,1.3,.12,.19);tie.rotation.y=-Math.atan2(direction.z,direction.x);const h=v.y-.3;if(h>4.15)this.block(group,'#7c8070',v.x,2+(h-4)/2,v.z,.13,h-4,.13);}
  if(p.station){const [x,z]=rotate(16,0,e.origin.direction);this.block(group,'#c2ab7e',(e.origin.x+x)/32*tile+half,e.origin.z/32*tile+.08,(e.origin.y+z)/32*tile+half,e.origin.direction%2?3.6:4,.16,e.origin.direction%2?4:3.6);}
 }
 update(packet){this.packet=packet;if(packet.scenery)this.setStatic(packet.scenery,packet.entry);this.actorIDs=[];let index=0;for(let i=0;i<packet.people.length;i+=6){const [id,x,z,y,phase,staff]=packet.people.slice(i,i+6);this.transform.position.set(x+half,y+.63,z+half);this.transform.rotation.set(0,0,0);this.transform.scale.set(.22,1.0,.22);this.transform.updateMatrix();this.actorBodies.setMatrixAt(index,this.transform.matrix);this.actorBodies.setColorAt(index,new THREE.Color(staff?phase===0?'#43749a':'#e0c18a':colors[id%colors.length]));this.transform.position.y=y+1.35;this.transform.scale.set(.23,.23,.23);this.transform.updateMatrix();this.actorHeads.setMatrixAt(index,this.transform.matrix);this.actorIDs.push({kind:staff?'staff':'guest',id});index++;}this.actorBodies.count=this.actorHeads.count=index;this.actorBodies.instanceMatrix.needsUpdate=this.actorHeads.instanceMatrix.needsUpdate=true;this.actorBodies.boundingSphere=this.actorHeads.boundingSphere=null;if(this.actorBodies.instanceColor)this.actorBodies.instanceColor.needsUpdate=true;
  let head=0;this.carIDs=[];for(let i=0;i<packet.cars.length;i++){const c=packet.cars[i],f=new THREE.Vector3(c.direction.x,c.direction.z,c.direction.y),up=new THREE.Vector3(c.up.x,c.up.z,c.up.y),side=new THREE.Vector3().crossVectors(f,up).normalize(),basis=new THREE.Matrix4().makeBasis(f,up,side),pos=new THREE.Vector3(c.position.x+half,c.position.z+.65,c.position.y+half);basis.setPosition(pos);this.carBodies.setMatrixAt(i,basis.clone().scale(new THREE.Vector3(1.8,.55,1.15)));const seat=basis.clone();seat.setPosition(pos.clone().addScaledVector(up,.38));this.carSeats.setMatrixAt(i,seat.scale(new THREE.Vector3(1.4,.2,.9)));this.carIDs.push({kind:'ride',id:c.ride});for(let j=0;j<c.occupants;j++){this.transform.position.copy(pos).addScaledVector(up,.75).addScaledVector(f,j?-.35:.35);this.transform.scale.set(.2,.2,.2);this.transform.rotation.set(0,0,0);this.transform.updateMatrix();this.carHeads.setMatrixAt(head++,this.transform.matrix);}}
  this.carBodies.count=this.carSeats.count=packet.cars.length;this.carHeads.count=head;this.carBodies.instanceMatrix.needsUpdate=this.carSeats.instanceMatrix.needsUpdate=this.carHeads.instanceMatrix.needsUpdate=true;this.carBodies.boundingSphere=this.carSeats.boundingSphere=null;
  let litter=0;for(let i=0;i<packet.litter.length;i+=4){const [id,x,z,y]=packet.litter.slice(i,i+4);this.transform.position.set(x+half,y+.05,z+half);this.transform.scale.set(.2,.03,.15);this.transform.rotation.set(0,id%5,0);this.transform.updateMatrix();this.litter.setMatrixAt(litter++,this.transform.matrix);}this.litter.count=litter;this.litter.instanceMatrix.needsUpdate=true;
 }
 pointer(event,height){const rect=this.renderer.domElement.getBoundingClientRect();this.mouse.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);this.ray.setFromCamera(this.mouse,this.camera);const p=this.ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),-height/32*tile),new THREE.Vector3());return p?{x:Math.floor(p.x/tile),y:Math.floor(p.z/tile)}:null;}
 pick(event){const rect=this.renderer.domElement.getBoundingClientRect();this.mouse.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);this.ray.setFromCamera(this.mouse,this.camera);for(const hit of this.ray.intersectObjects([this.staticGroup,this.actorBodies,this.actorHeads,this.carBodies,this.carSeats],true)){if(hit.object===this.actorBodies||hit.object===this.actorHeads)return this.actorIDs[hit.instanceId];if(hit.object===this.carBodies||hit.object===this.carSeats)return this.carIDs[hit.instanceId];let object=hit.object;while(object){if(object.userData.selection)return object.userData.selection;object=object.parent;}}return null;}
 preview(cells,ok){this.ghost.clear();this.ghostMaterial.color.set(ok?'#b3d873':'#d27456');for(const c of cells){const mesh=new THREE.Mesh(this.box,this.ghostMaterial);mesh.position.set(c.x*tile+half,c.low/32*tile+.15,c.y*tile+half);mesh.scale.set(tile,.18,tile);this.ghost.add(mesh);}}
 highlight(point){this.selection.visible=!!point;if(point)this.selection.position.set(point.x*tile+half,point.z/32*tile+.25,point.y*tile+half);}
 overview(){this.controls.target.set(82,4,74);this.camera.position.set(128,83,145);}
 close(){this.controls.target.set(80,4,72);this.camera.position.set(101,33,107);}
}
